import { unit, pyTask as T } from './programming.js';

function L(slug, title, body, terms, snippet, keyword, distractors, edge, tasks, points = []) {
  return { slug: `py-${slug}`, title, body, terms, points: [body, ...points],
    gap: ['Completa el ejemplo sin cambiar su significado.', snippet, keyword, distractors, `${keyword}: ${body}`],
    edge, tasks };
}
const E = (question, answer, wrong, why) => [question, [answer, ...wrong], why];

export default [
  unit('python-start', '1 · Enciende Python', 'Variables, números y tus primeras expresiones.', 'python', [
    L('variables', 'Tu primer programa', 'Una variable asocia un nombre con un valor. Python distingue mayúsculas y usa = para asignar. En este curso las entradas ya existen y tu respuesta se guarda en resultado.',
      [['=','Asigna un valor a un nombre'],['int','Representa un número entero'],['str','Representa texto']],
      'resultado ___ puntos', '=', ['==','!='],
      E('¿Puntos y puntos son la misma variable?', 'No, distingue mayúsculas', ['Sí, siempre','Solo con números'], 'Los identificadores distinguen mayúsculas y minúsculas.'), [
        T('Copia puntos a resultado.', 'resultado = puntos', [{puntos:10},{puntos:0},{puntos:-3}], 'La asignación copia el valor asociado al nombre.', {bug:'Resultado = puntos'}),
        T('Guarda en resultado el doble de monedas.', 'resultado = monedas * 2', [{monedas:4},{monedas:0},{monedas:13}], 'El operador * multiplica números.'),
        T('Guarda en resultado el texto de nombre.', 'resultado = nombre', [{nombre:'Ana'},{nombre:'Luis'},{nombre:''}], 'Las variables también pueden almacenar cadenas.'),
      ], ['No escribas las entradas a mano: cambian entre pruebas.', 'Ejecutar permite experimentar; Comprobar guarda tu respuesta y muestra la explicación.']),
    L('arithmetic', 'La calculadora del aventurero', 'Python respeta la prioridad matemática. / divide con decimales, // calcula cociente entero y % calcula resto.',
      [['//','Obtiene el cociente entero por división hacia abajo'],['%','Obtiene el resto de la división'],['**','Calcula una potencia']],
      'resultado = monedas ___ 3  # resto', '%', ['/','//'],
      E('¿Cuánto vale 7 // 2?', '3', ['3.5','1'], 'La división entera descarta la parte fraccionaria hacia menos infinito.'), [
        T('Calcula el coste de cantidad unidades a precio y guárdalo en resultado.', 'resultado = cantidad * precio', [{cantidad:3,precio:5},{cantidad:0,precio:9},{cantidad:2,precio:2.5}], 'Cantidad por precio produce el coste.', {bug:'resultado = cantidad + precio'}),
        T('Calcula grupos completos de 4 jugadores.', 'resultado = jugadores // 4', [{jugadores:9},{jugadores:4},{jugadores:3}], 'El cociente entero cuenta grupos completos.'),
        T('Calcula cuántos jugadores sobran al formar grupos de 4.', 'resultado = jugadores % 4', [{jugadores:9},{jugadores:4},{jugadores:3}], 'El resto representa lo que queda fuera de los grupos completos.'),
      ]),
    L('conversion', 'Cambia de tipo', 'int convierte texto numérico a entero, float a decimal y str a texto. Las conversiones pueden fallar si el contenido no es válido.',
      [['int','Convierte un valor compatible en entero'],['float','Convierte un valor compatible en decimal'],['str','Convierte un valor en texto']],
      'resultado = ___(texto) + 1  # entero', 'int', ['str','list'],
      E("¿Qué hace '2' + '3'?", "Produce '23'", ['Produce 5','Produce 6'], 'Con cadenas + concatena; convierte los datos antes de sumar.'), [
        T('Convierte texto en entero y súmale 10.', 'resultado = int(texto) + 10', [{texto:'7'},{texto:'0'},{texto:'-5'}], 'Convierte antes de operar.', {bug:'resultado = texto + 10'}),
        T('Convierte precio_texto a decimal y multiplícalo por cantidad.', 'resultado = float(precio_texto) * cantidad', [{precio_texto:'2.5',cantidad:4},{precio_texto:'0',cantidad:3},{precio_texto:'7.25',cantidad:2}], 'float admite un punto decimal.'),
        T("Construye el texto 'Nivel ' seguido del número nivel.", "resultado = 'Nivel ' + str(nivel)", [{nivel:1},{nivel:12},{nivel:0}], 'str permite concatenar un número a una cadena.'),
      ]),
  ]),
  unit('python-text', '2 · Domina el texto', 'Cadenas, índices, métodos y formatos.', 'python', [
    L('strings', 'Mensajes de misión', 'Una cadena es una secuencia inmutable de caracteres. Usa + para concatenar y len para medir; los espacios también cuentan.',
      [['len','Cuenta los elementos de una secuencia'],['Concatenación','Une cadenas sin modificar las originales'],['Cadena vacía','Texto con longitud cero']],
      'resultado = ___(nombre)', 'len', ['sum','max'],
      E("len('a b') devuelve…", '3', ['2','1'], 'El espacio es un carácter.'), [
        T('Guarda la longitud de mensaje en resultado.', 'resultado = len(mensaje)', [{mensaje:'Hola'},{mensaje:''},{mensaje:'a b'}], 'len cuenta todos los caracteres.', {bug:'resultado = mensaje'}),
        T("Saluda con 'Hola, ' seguido de nombre y '!'.", "resultado = 'Hola, ' + nombre + '!'", [{nombre:'Ana'},{nombre:'Leo'},{nombre:'SQL'}], 'Concatena piezas conservando puntuación y espacios.'),
        T('Repite simbolo exactamente veces veces.', 'resultado = simbolo * veces', [{simbolo:'*',veces:3},{simbolo:'ab',veces:2},{simbolo:'x',veces:0}], 'Multiplicar una cadena la repite.'),
      ]),
    L('slices', 'Recorta pistas', 'Los índices empiezan en cero; los negativos cuentan desde el final. En [inicio:fin], fin queda excluido.',
      [['[0]','Accede al primer elemento'],['[-1]','Accede al último elemento'],['[inicio:fin]','Extrae una porción sin incluir fin']],
      'resultado = texto[___]  # primer carácter', '0', ['1','-1'],
      E("'Python'[0:2] devuelve…", "'Py'", ["'Pyt'","'yt'"], 'El índice 2 no se incluye en la porción.'), [
        T('Obtén los primeros 3 caracteres de texto, incluso si es más corto.', 'resultado = texto[:3]', [{texto:'Python'},{texto:'SQL'},{texto:''}], 'Los slices permiten límites más allá de la longitud.', {bug:'resultado = texto[1:3]'}),
        T('Obtén los últimos 2 caracteres de texto.', 'resultado = texto[-2:]', [{texto:'Python'},{texto:'X'},{texto:''}], 'Un inicio negativo cuenta desde el final.'),
        T('Invierte texto usando un slice.', 'resultado = texto[::-1]', [{texto:'abc'},{texto:'radar'},{texto:''}], 'El paso -1 recorre en sentido inverso.'),
      ]),
    L('text-clean', 'Limpia y personaliza', 'strip elimina espacios extremos, lower normaliza y split separa. Los métodos crean un nuevo valor cuando trabajan con cadenas.',
      [['strip','Elimina espacios al principio y al final'],['lower','Devuelve una versión en minúsculas'],['f-string','Inserta expresiones dentro de una cadena']],
      'resultado = texto.strip().___()  # minúsculas', 'lower', ['upper','split'],
      E('texto.strip() modifica texto automáticamente…', 'No, devuelve una nueva cadena', ['Sí, siempre','Solo si empieza por espacio'], 'Las cadenas son inmutables.'), [
        T('Elimina espacios extremos y convierte texto a minúsculas.', 'resultado = texto.strip().lower()', [{texto:'  HOLA '},{texto:'Python'},{texto:'   '}], 'Encadena métodos para limpiar datos.', {bug:'resultado = texto.upper()'}),
        T('Separa frase por espacios en una lista de palabras.', 'resultado = frase.split()', [{frase:'hola mundo'},{frase:' a  b '},{frase:''}], 'split sin argumento agrupa espacios y omite trozos vacíos.'),
        T("Construye con f-string el mensaje '{nombre}: {puntos} XP'.", "resultado = f'{nombre}: {puntos} XP'", [{nombre:'Ana',puntos:10},{nombre:'Luis',puntos:0},{nombre:'Sol',puntos:42}], 'Las expresiones entre llaves se convierten a texto.'),
      ]),
  ]),
  unit('python-decisions', '3 · Elige tu camino', 'Comparaciones, lógica y decisiones.', 'python', [
    L('booleans', 'Verdadero o falso', 'Las comparaciones producen True o False. == compara; = asigna. and exige ambas condiciones y or permite cualquiera.',
      [['==','Compara si dos valores son iguales'],['and','Exige que ambas condiciones sean verdaderas'],['not','Invierte un valor lógico']],
      'resultado = edad ___ 18  # igualdad', '==', ['=','!='],
      E('False or True devuelve…', 'True', ['False','None'], 'or es verdadero si al menos una condición lo es.'), [
        T('Devuelve si edad es al menos 18.', 'resultado = edad >= 18', [{edad:17},{edad:18},{edad:30}], 'Comprueba también la frontera exacta.', {bug:'resultado = edad > 18'}),
        T('Devuelve si puntos>=10 y vidas>0.', 'resultado = puntos >= 10 and vidas > 0', [{puntos:10,vidas:1},{puntos:11,vidas:0},{puntos:9,vidas:2}], 'and combina requisitos.'),
        T('Devuelve si nombre NO está vacío.', "resultado = nombre != ''", [{nombre:''},{nombre:'Ana'},{nombre:' '}], 'Un espacio no equivale a una cadena vacía.'),
      ]),
    L('if-else', 'La puerta del nivel', 'if ejecuta un bloque si la condición es verdadera. else ofrece una alternativa. Dos puntos e indentación forman parte de la sintaxis.',
      [['if','Ejecuta un bloque si se cumple una condición'],['else','Ejecuta la alternativa cuando no se cumple'],['Indentación','Define qué instrucciones pertenecen al bloque']],
      'if puntos >= 10___\n    resultado = True', ':', [';','.'],
      E('¿Cuántos espacios se recomiendan por nivel de indentación?', '4', ['0','1 obligatorio'], 'Usa cuatro espacios y evita mezclar espacios con tabuladores.'), [
        T("Si puntos>=10 devuelve 'ganas'; si no, 'sigue'.", "if puntos >= 10:\n    resultado = 'ganas'\nelse:\n    resultado = 'sigue'", [{puntos:9},{puntos:10},{puntos:25}], 'Las ramas cubren ambos casos.', {bug:"if puntos > 10:\n    resultado = 'ganas'\nelse:\n    resultado = 'sigue'"}),
        T('Devuelve el mayor entre a y b utilizando if.', 'if a >= b:\n    resultado = a\nelse:\n    resultado = b', [{a:3,b:5},{a:4,b:4},{a:-1,b:-5}], 'Contempla también igualdad y números negativos.'),
        T('Si stock>0 devuelve precio*cantidad; si no devuelve 0.', 'if stock > 0:\n    resultado = precio * cantidad\nelse:\n    resultado = 0', [{stock:2,precio:5,cantidad:2},{stock:0,precio:5,cantidad:2},{stock:1,precio:0,cantidad:3}], 'La condición controla qué cálculo se realiza.'),
      ]),
    L('elif', 'Clasifica la aventura', 'elif encadena alternativas: solo se ejecuta la primera rama verdadera. Coloca los umbrales en un orden que no oculte casos.',
      [['elif','Comprueba otra condición si las anteriores fallan'],['Orden de ramas','Determina la primera condición que se ejecuta'],['Caso límite','Valor situado justo en un umbral']],
      "if nota >= 9:\n    resultado = 'oro'\n___ nota >= 5:\n    resultado = 'plata'", 'elif', ['else','for'],
      E('Si compruebas nota>=5 antes de nota>=9…', 'Las notas altas entran en la primera rama', ['Python reordena las ramas','Se ejecutan todas las ramas'], 'La primera condición verdadera gana.'), [
        T("Clasifica nota: >=9 'oro', >=5 'plata', el resto 'practica'.", "if nota >= 9:\n    resultado = 'oro'\nelif nota >= 5:\n    resultado = 'plata'\nelse:\n    resultado = 'practica'", [{nota:9},{nota:5},{nota:4}], 'Empieza por el umbral más alto.', {bug:"if nota >= 5:\n    resultado = 'plata'\nelif nota >= 9:\n    resultado = 'oro'\nelse:\n    resultado = 'practica'"}),
        T("Clasifica numero como 'positivo', 'cero' o 'negativo'.", "if numero > 0:\n    resultado = 'positivo'\nelif numero == 0:\n    resultado = 'cero'\nelse:\n    resultado = 'negativo'", [{numero:2},{numero:0},{numero:-2}], 'Los tres casos son excluyentes.'),
        T("Si vip devuelve 'prioridad'; si no y edad>=18 'normal'; en otro caso 'menor'.", "if vip:\n    resultado = 'prioridad'\nelif edad >= 18:\n    resultado = 'normal'\nelse:\n    resultado = 'menor'", [{vip:true,edad:10},{vip:false,edad:18},{vip:false,edad:17}], 'El orden expresa la prioridad del negocio.'),
      ]),
  ]),
  unit('python-loops', '4 · Automatiza los pasos', 'for, range, while y acumuladores.', 'python', [
    L('for-range', 'Repite sin aburrirte', 'for recorre elementos; range genera una secuencia de enteros y excluye el límite superior.',
      [['for','Recorre los elementos de un iterable'],['range','Genera una secuencia de enteros'],['Acumulador','Guarda un resultado que se actualiza en cada paso']],
      'for numero ___ range(3):\n    print(numero)', 'in', ['of','as'],
      E('list(range(3)) produce…', '[0, 1, 2]', ['[1, 2, 3]','[0, 1, 2, 3]'], 'El inicio por defecto es cero y el fin queda excluido.'), [
        T('Suma enteros del 1 al n inclusive; si n=0 devuelve 0.', 'resultado = 0\nfor numero in range(1, n + 1):\n    resultado += numero', [{n:4},{n:1},{n:0}], 'Inicializa el acumulador antes del bucle.', {bug:'resultado = 0\nfor numero in range(1, n):\n    resultado += numero'}),
        T('Construye una lista con los enteros de 0 a n-1.', 'resultado = []\nfor numero in range(n):\n    resultado.append(numero)', [{n:3},{n:0},{n:1}], 'append añade un elemento al final.'),
        T('Suma solo números pares del 0 al n inclusive.', 'resultado = 0\nfor numero in range(n + 1):\n    if numero % 2 == 0:\n        resultado += numero', [{n:6},{n:1},{n:0}], 'El resto cero detecta paridad.'),
      ]),
    L('while', 'Hasta alcanzar la meta', 'while repite mientras su condición sea verdadera. Actualiza el estado para que el bucle termine.',
      [['while','Repite mientras una condición sea verdadera'],['Actualización','Cambia el estado para acercarse a la salida'],['Bucle infinito','Repetición cuya condición nunca deja de cumplirse']],
      '___ monedas < meta:\n    monedas += 1', 'while', ['if','return'],
      E('Si olvidas actualizar el contador en while…', 'El bucle puede no terminar', ['Python lo incrementa solo','El bucle termina siempre al segundo paso'], 'La condición tiene que cambiar para salir.'), [
        T('Cuenta cuántos incrementos de 1 hacen falta de inicio a meta; si inicio>=meta devuelve 0.', 'actual = inicio\nresultado = 0\nwhile actual < meta:\n    actual += 1\n    resultado += 1', [{inicio:2,meta:5},{inicio:5,meta:5},{inicio:7,meta:4}], 'Actualiza valor y contador.', {bug:'actual = inicio\nresultado = 0\nwhile actual <= meta:\n    actual += 1\n    resultado += 1'}),
        T('Duplica valor hasta que alcance limite y devuelve el valor final. valor siempre es positivo.', 'resultado = valor\nwhile resultado < limite:\n    resultado *= 2', [{valor:2,limite:10},{valor:10,limite:5},{valor:1,limite:8}], 'El resultado puede superar el límite.'),
        T('Construye la cuenta atrás de n hasta 1 en una lista.', 'resultado = []\nactual = n\nwhile actual > 0:\n    resultado.append(actual)\n    actual -= 1', [{n:3},{n:0},{n:1}], 'Reducir actual garantiza la salida.'),
      ]),
    L('break-continue', 'Encuentra y salta', 'break termina el bucle; continue salta a la siguiente iteración. Diseña qué ocurre si no encuentras el elemento buscado.',
      [['break','Termina el bucle actual'],['continue','Salta al siguiente paso del bucle'],['Valor inicial','Representa el resultado si no se encuentra nada']],
      'for n in numeros:\n    if n < 0:\n        ___  # omitir negativos', 'continue', ['break','return'],
      E('break dentro de un bucle anidado termina…', 'Solo el bucle más interno', ['Todos los bucles del programa','El programa entero'], 'break se aplica al bucle al que pertenece.'), [
        T('Encuentra el primer número negativo de numeros; devuelve None si no hay.', 'resultado = None\nfor n in numeros:\n    if n < 0:\n        resultado = n\n        break', [{numeros:[2,-3,-5]},{numeros:[1,2]},{numeros:[]}], 'Salir al encontrarlo conserva el primer negativo.', {bug:'resultado = None\nfor n in numeros:\n    if n < 0:\n        resultado = n'}),
        T('Suma numeros omitiendo los negativos.', 'resultado = 0\nfor n in numeros:\n    if n < 0:\n        continue\n    resultado += n', [{numeros:[2,-3,5]},{numeros:[-1]},{numeros:[]}], 'continue omite el resto de la iteración.'),
        T('Devuelve números anteriores al primer 0 de numeros, sin incluir ese 0.', 'resultado = []\nfor n in numeros:\n    if n == 0:\n        break\n    resultado.append(n)', [{numeros:[1,2,0,3]},{numeros:[0,1]},{numeros:[2,3]}], 'El centinela marca dónde detenerse.'),
      ]),
  ]),
  unit('python-lists', '5 · Organiza tu inventario', 'Listas, mutabilidad, ordenación y tuplas.', 'python', [
    L('lists', 'La mochila de datos', 'Una lista almacena varios valores en orden y puede cambiar. append añade; pop extrae; los índices empiezan en cero.',
      [['append','Añade un elemento al final de una lista'],['pop','Extrae y devuelve un elemento'],['Lista','Secuencia ordenada y mutable']],
      'inventario.___(objeto)', 'append', ['add','push'],
      E('lista.append(x) devuelve…', 'None', ['La lista completa','x'], 'El método modifica la lista; no devuelve una nueva lista.'), [
        T('Copia inventario, añade objeto y guarda la lista en resultado.', 'resultado = inventario.copy()\nresultado.append(objeto)', [{inventario:['mapa'],objeto:'llave'},{inventario:[],objeto:'sol'},{inventario:[1,2],objeto:3}], 'Copia antes de modificar si quieres conservar la entrada.', {bug:'resultado = inventario.append(objeto)'}),
        T('Devuelve el primer elemento de items o None si está vacío.', 'resultado = items[0] if items else None', [{items:[4,5]},{items:[]},{items:['a']}], 'Comprueba la lista antes de acceder al índice cero.'),
        T('Devuelve una copia de items sin el último elemento.', 'resultado = items[:-1]', [{items:[1,2,3]},{items:[1]},{items:[]}], 'Un slice crea otra lista.'),
      ]),
    L('sorting', 'Ordena la mochila', 'sorted devuelve una nueva lista; sort modifica la existente. reverse=True cambia a orden descendente.',
      [['sorted','Devuelve una nueva lista ordenada'],['sort','Ordena una lista en el sitio'],['reverse=True','Solicita orden descendente']],
      'resultado = sorted(numeros, ___=True)', 'reverse', ['desc','ascending'],
      E('resultado = numeros.sort() guarda…', 'None', ['Una lista ordenada','La lista invertida'], 'sort modifica numeros y devuelve None.'), [
        T('Ordena numeros de menor a mayor sin modificar la entrada.', 'resultado = sorted(numeros)', [{numeros:[3,1,2]},{numeros:[]},{numeros:[-2,4,-2]}], 'sorted acepta cualquier iterable y crea una lista.', {bug:'resultado = numeros.sort()'}),
        T('Devuelve los 2 números mayores, de mayor a menor.', 'resultado = sorted(numeros, reverse=True)[:2]', [{numeros:[3,1,9]},{numeros:[4]},{numeros:[]}], 'Ordena antes de recortar.'),
        T('Ordena palabras por longitud; conserva el orden original en empates.', 'resultado = sorted(palabras, key=len)', [{palabras:['sql','a','py']},{palabras:['bb','aa']},{palabras:[]}], 'La ordenación de Python es estable.'),
      ]),
    L('tuples-copy', 'Copia y desempaqueta', 'Una tupla es inmutable. El desempaquetado asigna elementos a varios nombres. La copia superficial duplica el contenedor, no sus objetos internos.',
      [['Tupla','Secuencia cuyo contenedor no puede modificarse'],['Desempaquetado','Asigna varios elementos a varios nombres'],['Copia superficial','Copia el contenedor pero comparte objetos internos']],
      'x, y ___ punto', '=', ['==','in'],
      E('b = a copia una lista…', 'No, ambos nombres apuntan a la misma lista', ['Sí, siempre','Solo si tiene números'], 'La asignación no duplica el objeto.'), [
        T('Desempaqueta punto=(x,y) y devuelve x+y.', 'x, y = punto\nresultado = x + y', [{punto:[2,3]},{punto:[0,0]},{punto:[-2,1]}], 'El número de variables debe coincidir con los elementos.', {bug:'x, y = punto\nresultado = x - y'}),
        T('Convierte items a una tupla.', 'resultado = tuple(items)', [{items:[1,2]},{items:[]},{items:['a']}], 'tuple crea una secuencia inmutable.'),
        T('Copia items y cambia solo el primer elemento por nuevo; si está vacío deja [].', 'resultado = items.copy()\nif resultado:\n    resultado[0] = nuevo', [{items:[1,2],nuevo:9},{items:[],nuevo:9},{items:['a'],nuevo:'b'}], 'La copia evita modificar el contenedor de origen.'),
      ]),
  ]),
  unit('python-dicts', '6 · Diccionarios y conjuntos', 'Claves, recuentos y eliminación de duplicados.', 'python', [
    L('dicts', 'La ficha del personaje', 'Un diccionario relaciona claves con valores. get permite dar un valor por defecto cuando la clave no existe.',
      [['dict','Relaciona claves únicas con valores'],['get','Busca una clave con un valor alternativo'],['items','Recorre parejas de clave y valor']],
      "resultado = ficha.___('puntos',0)", 'get', ['find','index'],
      E("ficha['puntos'] si no existe la clave…", 'Lanza KeyError', ['Devuelve 0','Crea la clave'], 'get evita el error si un valor alternativo es apropiado.'), [
        T('Devuelve puntos de ficha o 0 si no existe.', "resultado = ficha.get('puntos',0)", [{ficha:{puntos:10}},{ficha:{}},{ficha:{puntos:0}}], 'get diferencia ausencia de valores existentes.', {bug:"resultado = ficha['puntos']"}),
        T('Copia ficha y añade nivel con el valor nivel.', "resultado = ficha.copy()\nresultado['nivel'] = nivel", [{ficha:{nombre:'Ana'},nivel:2},{ficha:{nivel:1},nivel:3},{ficha:{},nivel:0}], 'Asignar una clave existente actualiza su valor.'),
        T('Devuelve las claves de ficha ordenadas alfabéticamente.', 'resultado = sorted(ficha.keys())', [{ficha:{b:2,a:1}},{ficha:{}},{ficha:{sql:1}}], 'Recorrer un diccionario directamente también recorre claves.'),
      ]),
    L('frequency', 'Cuenta tesoros repetidos', 'Los diccionarios sirven para acumular métricas por clave. Inicializa cada clave con get antes de actualizarla.',
      [['Frecuencia','Número de apariciones por valor'],['get(clave,0)','Inicializa una cuenta ausente en cero'],['items','Permite recorrer nombres y cantidades']],
      'cuentas[item] = cuentas.get(item,0) ___ 1', '+', ['-','*'],
      E('Una lista vacía de entradas produce un recuento…', '{}', ['None','{0: 1}'], 'No hay claves que contar.'), [
        T('Cuenta las apariciones de cada palabra en palabras.', 'resultado = {}\nfor palabra in palabras:\n    resultado[palabra] = resultado.get(palabra,0) + 1', [{palabras:['sql','py','sql']},{palabras:[]},{palabras:['x','x']}], 'El diccionario acumula por identidad de palabra.', {bug:'resultado = {}\nfor palabra in palabras:\n    resultado[palabra] = 1'}),
        T('Suma los valores del diccionario inventario.', 'resultado = sum(inventario.values())', [{inventario:{oro:3,plata:4}},{inventario:{}},{inventario:{oro:0}}], 'values obtiene cantidades sin las claves.'),
        T('Devuelve claves de inventario cuyo valor es 0, alfabéticamente.', 'resultado = []\nfor clave,valor in inventario.items():\n    if valor == 0:\n        resultado.append(clave)\nresultado = sorted(resultado)', [{inventario:{oro:0,plata:2}},{inventario:{b:0,a:0}},{inventario:{}}], 'items permite filtrar por valor y devolver claves.'),
      ]),
    L('sets', 'Colección sin repetidos', 'Un set almacena valores únicos sin un orden de presentación garantizado. Las operaciones de conjuntos comparan pertenencia.',
      [['set','Colección de elementos únicos'],['intersection','Elementos comunes a dos conjuntos'],['difference','Elementos del primero ausentes en el segundo']],
      'resultado = sorted(___(items))', 'set', ['list','tuple'],
      E('Para mostrar un set de forma reproducible…', 'Ordénalo antes de mostrarlo', ['Confía en su orden de inserción','Añade duplicados'], 'sorted fija un orden claro para la salida.'), [
        T('Devuelve items únicos ordenados.', 'resultado = sorted(set(items))', [{items:[3,1,3]},{items:[]},{items:['b','a','b']}], 'set elimina repeticiones y sorted ordena.', {bug:'resultado = sorted(items)'}),
        T('Devuelve elementos comunes de a y b ordenados.', 'resultado = sorted(set(a).intersection(b))', [{a:[1,2],b:[2,3]},{a:[],b:[1]},{a:[3,3],b:[3]}], 'La intersección conserva valores compartidos.'),
        T('Devuelve elementos de a que faltan en b, únicos y ordenados.', 'resultado = sorted(set(a).difference(b))', [{a:[1,2],b:[2,3]},{a:[1],b:[]},{a:[],b:[1]}], 'La diferencia es direccional.'),
      ]),
  ]),
  unit('python-functions', '7 · Construye herramientas', 'Funciones, argumentos, retorno y alcance.', 'python', [
    L('functions', 'Una herramienta reutilizable', 'def crea una función; los parámetros reciben datos y return entrega un resultado. Imprimir no equivale a devolver.',
      [['def','Define una función'],['return','Entrega el resultado de una función'],['Parámetro','Nombre que recibe un argumento al llamar']],
      'def doble(n):\n    ___ n * 2', 'return', ['print','break'],
      E('Una función sin return explícito devuelve…', 'None', ['0','El último valor calculado'], 'El retorno implícito es None.'), [
        T('Define doble(n), que devuelve n*2; llama con numero y guarda en resultado.', 'def doble(n):\n    return n * 2\nresultado = doble(numero)', [{numero:3},{numero:0},{numero:-2}], 'El retorno permite usar el valor fuera de la función.', {bug:'def doble(n):\n    print(n * 2)\nresultado = doble(numero)'}),
        T('Define area(base,altura) que devuelve base*altura y llama con b,h.', 'def area(base,altura):\n    return base * altura\nresultado = area(b,h)', [{b:3,h:4},{b:0,h:8},{b:2,h:2.5}], 'Los argumentos se asignan por posición.'),
        T('Define es_par(n) y llama con numero; resultado debe ser booleano.', 'def es_par(n):\n    return n % 2 == 0\nresultado = es_par(numero)', [{numero:4},{numero:3},{numero:0}], 'Una comparación produce el valor booleano que retorna la función.'),
      ]),
    L('default-args', 'Herramientas configurables', 'Los argumentos con nombre hacen llamadas legibles. Los valores por defecto se evalúan una vez; evita listas mutables como defecto.',
      [['Argumento con nombre','Asocia un valor a un parámetro explícito'],['Valor por defecto','Se usa cuando no envías ese argumento'],['None como defecto','Permite crear un contenedor nuevo por llamada']],
      'def saludar(nombre, saludo___"Hola"):\n    return saludo + nombre', '=', ['==',':'],
      E('Una lista como argumento por defecto puede…', 'Compartirse entre llamadas', ['Recrearse siempre','Ser inmutable'], 'Los valores por defecto se crean al definir la función.'), [
        T("Define saludar(nombre,saludo='Hola') devolviendo saludo+', '+nombre. Usa nombre y saludo de entrada.", "def saludar(nombre,saludo='Hola'):\n    return saludo + ', ' + nombre\nresultado = saludar(nombre,saludo=saludo)", [{nombre:'Ana',saludo:'Hola'},{nombre:'Luis',saludo:'Buenas'},{nombre:'Sol',saludo:'Hey'}], 'Los argumentos con nombre aclaran la llamada.', {bug:"def saludar(nombre,saludo='Hola'):\n    return 'Hola, ' + nombre\nresultado = saludar(nombre,saludo=saludo)"}),
        T('Define multiplicar(n,factor=2). Devuelve [multiplicar(n),multiplicar(n,factor=3)].', 'def multiplicar(n,factor=2):\n    return n * factor\nresultado = [multiplicar(n),multiplicar(n,factor=3)]', [{n:2},{n:0},{n:-1}], 'El defecto puede sustituirse por un argumento explícito.'),
        T('Define agregar(x,items=None) que crea una lista nueva si falta. Devuelve [agregar(a),agregar(b)].', 'def agregar(x,items=None):\n    if items is None:\n        items = []\n    items.append(x)\n    return items\nresultado = [agregar(a),agregar(b)]', [{a:1,b:2},{a:'x',b:'y'},{a:0,b:0}], 'None impide compartir una lista mutable entre llamadas.'),
      ]),
    L('scope', 'Cada función tiene su mochila', 'Las variables locales pertenecen a una llamada. Pasa entradas como parámetros y devuelve resultados en vez de depender de estado global.',
      [['Variable local','Nombre definido dentro de una función'],['Argumento','Valor enviado al llamar una función'],['Función pura','Calcula sin modificar estado externo']],
      'def sumar(a,b):\n    total = a+b\n    ___ total', 'return', ['break','continue'],
      E('Una variable local definida en una función está disponible fuera automáticamente…', 'No', ['Sí','Solo después de imprimirla'], 'Devuelve el dato que necesites para sacarlo de la función.'), [
        T('Define descontar(precio,porcentaje) y calcula precio*(1-porcentaje/100), redondeado a 2 decimales.', 'def descontar(precio,porcentaje):\n    return round(precio * (1-porcentaje/100),2)\nresultado = descontar(precio,porcentaje)', [{precio:100,porcentaje:20},{precio:10,porcentaje:0},{precio:30,porcentaje:10}], 'La función calcula exclusivamente a partir de sus parámetros.', {bug:'def descontar(precio,porcentaje):\n    return precio - porcentaje\nresultado = descontar(precio,porcentaje)'}),
        T('Define sumar(items) con un acumulador local y llama con numeros.', 'def sumar(items):\n    total = 0\n    for item in items:\n        total += item\n    return total\nresultado = sumar(numeros)', [{numeros:[1,2]},{numeros:[]},{numeros:[-2,5]}], 'Cada llamada inicializa su propio acumulador.'),
        T('Define normalizar(texto) que hace strip y lower, y aplícala a cada elemento de nombres.', 'def normalizar(texto):\n    return texto.strip().lower()\nresultado = []\nfor nombre in nombres:\n    resultado.append(normalizar(nombre))', [{nombres:[' ANA ','Luis']},{nombres:[]},{nombres:[' SQL ']}], 'Reutiliza una transformación en una colección.'),
      ]),
  ]),
  unit('python-comprehensions', '8 · Python expresivo', 'Comprensiones, enumerate, zip y generadores.', 'python', [
    L('comprehensions', 'Transforma de un vistazo', 'Una comprensión expresa transformar y filtrar una colección. Empieza con un bucle normal y úsala cuando haga el código más claro.',
      [['Comprensión','Construye una colección mediante una expresión y un recorrido'],['Expresión','Calcula cada valor de salida'],['Filtro if','Decide qué entradas incluir']],
      'resultado = [n*2 ___ n in numeros]', 'for', ['while','return'],
      E('[n for n in []] produce…', '[]', ['None','[0]'], 'Sin elementos de entrada, la comprensión no produce valores.'), [
        T('Devuelve el cuadrado de cada valor de numeros.', 'resultado = [n*n for n in numeros]', [{numeros:[1,2,3]},{numeros:[]},{numeros:[-2,0]}], 'La expresión se aplica a cada elemento.', {bug:'resultado = [n*2 for n in numeros]'}),
        T('Devuelve solo positivos de numeros en el mismo orden.', 'resultado = [n for n in numeros if n > 0]', [{numeros:[-1,0,2]},{numeros:[]},{numeros:[3,1]}], 'El if decide inclusión, no transforma el valor.'),
        T('Construye un diccionario palabra -> longitud para palabras.', 'resultado = {palabra:len(palabra) for palabra in palabras}', [{palabras:['sql','python']},{palabras:[]},{palabras:['a','a']}], 'Las claves repetidas conservan su último valor.'),
      ]),
    L('enumerate-zip', 'Índices y parejas', 'enumerate entrega posición y valor; zip agrupa entradas por posición y termina cuando se agota la más corta.',
      [['enumerate','Produce parejas de índice y elemento'],['zip','Agrupa elementos de iterables por posición'],['start=1','Hace empezar los índices de enumerate en uno']],
      'for posicion,nombre in ___(nombres,start=1):\n    print(posicion,nombre)', 'enumerate', ['range','sorted'],
      E('zip([1,2,3],[4]) produce…', 'Una pareja: (1,4)', ['Tres parejas','Un error siempre'], 'zip sin strict termina con el iterable más corto.'), [
        T('Devuelve etiquetas numeradas desde 1 con formato 1:Ana para nombres.', "resultado = [f'{i}:{nombre}' for i,nombre in enumerate(nombres,start=1)]", [{nombres:['Ana','Luis']},{nombres:[]},{nombres:['Sol']}], 'enumerate evita mantener un contador manual.', {bug:"resultado = [f'{i}:{nombre}' for i,nombre in enumerate(nombres)]"}),
        T('Suma a y b elemento a elemento hasta la longitud de la lista más corta.', 'resultado = [x+y for x,y in zip(a,b)]', [{a:[1,2],b:[3,4]},{a:[1,2],b:[5]},{a:[],b:[1]}], 'zip combina elementos correspondientes.'),
        T('Construye un diccionario de nombres a puntos usando zip.', 'resultado = dict(zip(nombres,puntos))', [{nombres:['Ana','Luis'],puntos:[10,5]},{nombres:[],puntos:[]},{nombres:['Sol'],puntos:[0]}], 'dict acepta pares clave-valor.'),
      ]),
    L('generators', 'Procesa sin acumularlo todo', 'Un generador produce valores bajo demanda. Una expresión generadora usa paréntesis y puede consumirse con sum, any o list.',
      [['Generador','Produce valores cuando se solicitan'],['yield','Entrega un valor y pausa la función generadora'],['any','Comprueba si algún elemento es verdadero']],
      'def contar(n):\n    for i in range(n):\n        ___ i', 'yield', ['return','break'],
      E('Después de consumir totalmente un generador…', 'No puedes recorrerlo de nuevo sin recrearlo', ['Se reinicia solo','Se convierte en lista'], 'Los generadores mantienen un estado de consumo.'), [
        T('Suma cuadrados de numeros con una expresión generadora.', 'resultado = sum(n*n for n in numeros)', [{numeros:[2,3]},{numeros:[]},{numeros:[-1,0]}], 'sum consume los valores sin necesitar una lista intermedia.', {bug:'resultado = sum(n for n in numeros)'}),
        T('Devuelve si algún valor de numeros es negativo.', 'resultado = any(n < 0 for n in numeros)', [{numeros:[1,-1]},{numeros:[]},{numeros:[0,2]}], 'any termina cuando encuentra True.'),
        T('Define un generador pares(n) que entrega 0,2,... hasta n inclusive y guarda list(pares(n)).', 'def pares(n):\n    for i in range(0,n+1,2):\n        yield i\nresultado = list(pares(n))', [{n:5},{n:0},{n:2}], 'yield entrega varios resultados a lo largo de la función.'),
      ]),
  ]),
  unit('python-errors', '9 · Aprende de los errores', 'Excepciones, validación y módulos de la biblioteca estándar.', 'python', [
    L('exceptions', 'Un fallo con salida', 'try ejecuta código que puede fallar; except captura un tipo concreto. Evita capturar cualquier error y ocultar fallos de programación.',
      [['try','Ejecuta un bloque que puede lanzar una excepción'],['except','Gestiona una excepción determinada'],['ValueError','Indica un valor incompatible con la operación']],
      'try:\n    resultado = int(texto)\n___ ValueError:\n    resultado = None', 'except', ['else','if'],
      E('int(\'hola\') lanza…', 'ValueError', ['KeyError','ZeroDivisionError'], 'El texto no representa un entero válido.'), [
        T('Convierte texto a int; devuelve None si ocurre ValueError.', 'try:\n    resultado = int(texto)\nexcept ValueError:\n    resultado = None', [{texto:'12'},{texto:'hola'},{texto:'-2'}], 'Captura solo el fallo esperado.', {bug:'resultado = int(texto)'}),
        T('Divide a entre b; devuelve None si b es cero.', 'try:\n    resultado = a / b\nexcept ZeroDivisionError:\n    resultado = None', [{a:6,b:2},{a:1,b:0},{a:0,b:3}], 'Una división por cero es una excepción específica.'),
        T('Busca clave en datos; devuelve "ausente" si hay KeyError.', "try:\n    resultado = datos[clave]\nexcept KeyError:\n    resultado = 'ausente'", [{datos:{x:3},clave:'x'},{datos:{},clave:'x'},{datos:{x:0},clave:'x'}], 'La excepción distingue ausencia de un valor existente.'),
      ]),
    L('validation', 'Entradas confiables', 'Valida límites y formatos antes de operar. Una entrada vacía no debería provocar un acceso a índices inexistentes.',
      [['Validación','Comprueba si una entrada cumple los requisitos'],['isinstance','Comprueba si un valor pertenece a un tipo'],['Caso vacío','Entrada sin elementos que merece una regla explícita']],
      'resultado = ___(valor,int)', 'isinstance', ['len','sum'],
      E('Para calcular una media de una lista vacía…', 'Define una salida antes de dividir por len', ['Divide por cero','Usa siempre el primer elemento'], 'El comportamiento del caso vacío debe ser deliberado.'), [
        T('Devuelve la media de numeros o None si la lista está vacía.', 'resultado = sum(numeros)/len(numeros) if numeros else None', [{numeros:[2,4]},{numeros:[]},{numeros:[0]}], 'Evita división por cero y documenta la ausencia.', {bug:'resultado = sum(numeros)/len(numeros)'}),
        T('Devuelve True si edad está entre 0 y 120 inclusive.', 'resultado = 0 <= edad <= 120', [{edad:0},{edad:120},{edad:-1},{edad:121}], 'Prueba ambas fronteras y valores exteriores.'),
        T('Convierte texto en entero no negativo; devuelve None si es inválido o negativo.', 'try:\n    numero = int(texto)\n    resultado = numero if numero >= 0 else None\nexcept ValueError:\n    resultado = None', [{texto:'5'},{texto:'-1'},{texto:'abc'},{texto:'0'}], 'Combina validación sintáctica y semántica.'),
      ]),
    L('modules', 'Tu caja de herramientas', 'import permite reutilizar módulos. math ofrece funciones matemáticas y json transforma datos entre texto y estructuras.',
      [['import','Carga un módulo y permite usar sus herramientas'],['math.sqrt','Calcula una raíz cuadrada'],['json.loads','Convierte texto JSON en estructuras de Python']],
      '___ math\nresultado = math.sqrt(numero)', 'import', ['include','require'],
      E('import math permite usar sqrt normalmente como…', 'math.sqrt(numero)', ['sqrt(numero) sin importar el nombre','numero.sqrt()'], 'El módulo agrupa sus funciones bajo su nombre.'), [
        T('Importa math y calcula la raíz cuadrada de numero.', 'import math\nresultado = math.sqrt(numero)', [{numero:9},{numero:0},{numero:2.25}], 'La raíz de estos números no negativos es válida.', {bug:'import math\nresultado = math.floor(numero)'}),
        T('Importa math y redondea numero hacia arriba.', 'import math\nresultado = math.ceil(numero)', [{numero:2.2},{numero:3},{numero:-1.8}], 'ceil obtiene el menor entero mayor o igual al valor.'),
        T('Importa json, convierte texto JSON en un diccionario y devuelve su clave puntos o 0.', "import json\ndatos = json.loads(texto)\nresultado = datos.get('puntos',0)", [{texto:'{"puntos":12}'},{texto:'{}'},{texto:'{"puntos":0}'}], 'Tras parsear JSON puedes usar herramientas de diccionario.'),
      ]),
  ]),
  unit('python-files', '10 · Lee y prepara datos', 'Archivos de ejemplo, CSV sencillo y JSON.', 'python', [
    L('files', 'Abre el cofre de datos', 'with cierra el archivo incluso si hay un error. En Habla open solo lee los archivos virtuales del ejercicio; no toca tus archivos personales.',
      [['with','Gestiona un recurso y lo cierra al salir'],['open','Abre un archivo de ejemplo para lectura'],['read','Lee el contenido del archivo']],
      "with open('notas.txt') ___ archivo:\n    resultado = archivo.read()", 'as', ['in','is'],
      E('¿Qué ocurre al salir de with open(...)?', 'Se cierra el archivo', ['Se borra el archivo','Se cambia a mayúsculas'], 'El gestor de contexto libera el recurso.'), [
        T("Lee todo 'notas.txt' y guarda el texto en resultado.", "with open('notas.txt') as archivo:\n    resultado = archivo.read()", [{},{},{}], 'with administra la vida del archivo.', {bug:"with open('notas.txt') as archivo:\n    resultado = archivo.readline()",files:[{'notas.txt':'SQL\nPython\n'},{'notas.txt':''},{'notas.txt':'uno\ndos'}]}),
        T("Lee 'notas.txt' y devuelve una lista de líneas no vacías, sin espacios extremos.", "with open('notas.txt') as archivo:\n    resultado = [linea.strip() for linea in archivo if linea.strip()]", [{},{},{}], 'El archivo es iterable por líneas.', {files:[{'notas.txt':' SQL \n\n Python\n'},{'notas.txt':''},{'notas.txt':' x \n'}]}),
        T("Lee 'notas.txt' y cuenta sus líneas con readlines.", "with open('notas.txt') as archivo:\n    resultado = len(archivo.readlines())", [{},{},{}], 'readlines conserva las líneas, incluso vacías.', {files:[{'notas.txt':'a\nb\n'},{'notas.txt':''},{'notas.txt':'\n'}]}),
      ]),
    L('csv-simple', 'Una tabla en texto', 'Un CSV simple separa campos con comas y filas con saltos de línea. Este ejercicio no incluye comillas ni comas dentro de campos; para CSV general usa csv en un proyecto real.',
      [['split','Divide una cadena por un separador'],['Cabecera','Primera fila que nombra las columnas'],['Conversión','Transforma valores de texto a números']],
      "campos = linea.___(',')", 'split', ['join','strip'],
      E('Separar por coma es suficiente para CSV con campos entrecomillados que contienen comas…', 'No, necesitas un parser CSV', ['Sí, siempre','Solo si son números'], 'El módulo csv entiende comillas y separadores dentro de campos.'), [
        T('texto contiene nombre,puntos por línea sin cabecera. Devuelve la suma de puntos; omite líneas vacías.', "resultado = 0\nfor linea in texto.split('\\n'):\n    if linea.strip():\n        nombre,puntos = linea.split(',')\n        resultado += int(puntos)", [{texto:'Ana,10\nLuis,5'},{texto:''},{texto:'Sol,0\n'}], 'Separa líneas y campos y convierte antes de sumar.', {bug:"resultado = 0\nfor linea in texto.split('\\n'):\n    if linea.strip():\n        nombre,puntos = linea.split(',')\n        resultado += puntos"}),
        T('Devuelve los nombres de texto CSV nombre,puntos por línea sin cabecera; omite líneas vacías.', "resultado = [linea.split(',')[0] for linea in texto.split('\\n') if linea.strip()]", [{texto:'Ana,10\nLuis,5'},{texto:''},{texto:'Sol,0'}], 'Selecciona el primer campo de cada registro.'),
        T('texto CSV tiene cabecera nombre,puntos. Devuelve lista de puntos enteros omitiendo cabecera y líneas vacías.', "lineas = texto.split('\\n')[1:]\nresultado = [int(linea.split(',')[1]) for linea in lineas if linea.strip()]", [{texto:'nombre,puntos\nAna,10\nLuis,5'},{texto:'nombre,puntos'},{texto:'nombre,puntos\nSol,0\n'}], 'La cabecera no es un registro de datos.'),
      ]),
    L('json', 'Datos que viajan', 'JSON representa objetos, listas y valores simples. loads lee texto y dumps serializa; los booleanos y nulos cambian de notación.',
      [['json.loads','Deserializa texto JSON'],['json.dumps','Serializa datos a texto JSON'],['null','Se convierte en None al leer JSON']],
      'import json\nresultado = json.___(texto)', 'loads', ['dumps','read'],
      E('JSON true se convierte en Python…', 'True', ["'true'",'1 como texto'], 'JSON y Python tienen notaciones distintas para algunos valores.'), [
        T('Lee texto JSON, que contiene una lista de números, y devuelve su suma.', 'import json\nresultado = sum(json.loads(texto))', [{texto:'[1,2,3]'},{texto:'[]'},{texto:'[-1,1]'}], 'Parsea antes de sumar.', {bug:'import json\nresultado = len(json.loads(texto))'}),
        T('Serializa datos a JSON con claves ordenadas (sort_keys=True).', 'import json\nresultado = json.dumps(datos,sort_keys=True)', [{datos:{b:2,a:1}},{datos:{}},{datos:{activo:true,nulo:null}}], 'Ordenar claves hace la representación reproducible.'),
        T('Lee texto JSON de una lista de objetos y devuelve nombres cuyo campo activo es true.', "import json\nresultado = [p['nombre'] for p in json.loads(texto) if p.get('activo',False)]", [{texto:'[{"nombre":"Ana","activo":true},{"nombre":"Luis","activo":false}]'},{texto:'[]'},{texto:'[{"nombre":"Sol"}]'}], 'Combina parsing, filtro y proyección.'),
      ]),
  ]),
  unit('python-objects', '11 · Objetos y pruebas', 'Clases sencillas, métodos y contratos de funciones.', 'python', [
    L('classes', 'Crea tu personaje', 'Una clase define un tipo de objeto. self representa la instancia dentro de un método. Para este laboratorio usa atributos públicos como name, price y balance.',
      [['class','Define un tipo de objeto'],['self','Representa la instancia dentro de un método'],['Atributo','Dato asociado a un objeto']],
      '___ Personaje:\n    name = "Ana"', 'class', ['def','object'],
      E('Dos instancias de una clase son…', 'Objetos distintos', ['La misma variable siempre','Dos módulos'], 'Cada instancia puede mantener sus propios atributos.'), [
        T('Define Personaje, crea p, asigna p.name=nombre y guarda p.name en resultado.', 'class Personaje:\n    pass\np = Personaje()\np.name = nombre\nresultado = p.name', [{nombre:'Ana'},{nombre:'Leo'},{nombre:''}], 'Los atributos pertenecen a la instancia.', {bug:"class Personaje:\n    pass\np = Personaje()\np.name = 'Ana'\nresultado = p.name"}),
        T('Define Producto, crea p con price=precio y devuelve p.price*cantidad.', 'class Producto:\n    pass\np = Producto()\np.price = precio\nresultado = p.price * cantidad', [{precio:5,cantidad:3},{precio:0,cantidad:3},{precio:2.5,cantidad:2}], 'La clase agrupa datos de una entidad.'),
        T('Crea dos instancias de Personaje con name=a y name=b y devuelve sus nombres en una lista.', 'class Personaje:\n    pass\np = Personaje()\nq = Personaje()\np.name = a\nq.name = b\nresultado = [p.name,q.name]', [{a:'Ana',b:'Luis'},{a:'X',b:'Y'},{a:'',b:'Sol'}], 'Modificar una instancia no cambia la otra.'),
      ]),
    L('methods', 'Objetos con acciones', 'Un método es una función de la clase. Recibe self para leer o actualizar el estado de esa instancia.',
      [['Método','Función definida dentro de una clase'],['self.balance','Estado de saldo de una instancia'],['Encapsulación','Agrupa datos y operaciones relacionadas']],
      'class Cuenta:\n    def deposit(___,cantidad):\n        self.balance += cantidad', 'self', ['class','return'],
      E('Un método debe recibir self como primer parámetro convencional…', 'Sí, si es un método de instancia', ['No, nunca','Solo si devuelve texto'], 'Python pasa la instancia automáticamente al llamar al método.'), [
        T('Define Cuenta con deposit(self,cantidad) que aumenta balance. Crea cuenta con saldo inicial, deposita importe y devuelve balance.', 'class Cuenta:\n    def deposit(self,cantidad):\n        self.balance += cantidad\ncuenta = Cuenta()\ncuenta.balance = saldo\ncuenta.deposit(importe)\nresultado = cuenta.balance', [{saldo:10,importe:5},{saldo:0,importe:0},{saldo:2,importe:3}], 'El método actualiza la instancia.', {bug:'class Cuenta:\n    def deposit(self,cantidad):\n        self.balance = cantidad\ncuenta = Cuenta()\ncuenta.balance = saldo\ncuenta.deposit(importe)\nresultado = cuenta.balance'}),
        T('Define Producto.total(self,cantidad) devolviendo self.price*cantidad y úsalo con precio,cantidad.', 'class Producto:\n    def total(self,cantidad):\n        return self.price * cantidad\np = Producto()\np.price = precio\nresultado = p.total(cantidad)', [{precio:5,cantidad:2},{precio:0,cantidad:3},{precio:1.5,cantidad:4}], 'El método combina estado y un argumento.'),
        T("Define Persona.label(self) devolviendo 'Hola, '+self.name. Crea persona con nombre y llama label.", "class Persona:\n    def label(self):\n        return 'Hola, ' + self.name\np = Persona()\np.name = nombre\nresultado = p.label()", [{nombre:'Ana'},{nombre:'Leo'},{nombre:''}], 'El método lee atributos de su instancia.'),
      ]),
    L('tests', 'Prueba tus herramientas', 'Una función debe tener un contrato claro: entrada, salida y casos extremos. assert expresa una expectativa y falla si no se cumple.',
      [['assert','Comprueba una expectativa y falla si no se cumple'],['Caso límite','Comprueba extremos como cero y colecciones vacías'],['Regresión','Error que vuelve después de un cambio']],
      '___ 2+2 == 4', 'assert', ['except','while'],
      E('Probar solo el caso normal permite detectar todos los errores…', 'No, añade fronteras y casos vacíos', ['Sí','Solo si la función es corta'], 'Los errores suelen aparecer en fronteras y ausencias.'), [
        T('Define media(xs) devolviendo None si está vacío. Añade assert media([]) is None y calcula media(numeros).', 'def media(xs):\n    return sum(xs)/len(xs) if xs else None\nassert media([]) is None\nresultado = media(numeros)', [{numeros:[2,4]},{numeros:[]},{numeros:[0]}], 'Una expectativa concreta documenta el caso vacío.', {bug:'def media(xs):\n    return sum(xs)/len(xs)\nassert media([]) is None\nresultado = media(numeros)'}),
        T('Define limitar(n) entre 0 y 100, comprueba los extremos con assert y calcula limitar(numero).', 'def limitar(n):\n    return min(100,max(0,n))\nassert limitar(-1) == 0\nassert limitar(101) == 100\nresultado = limitar(numero)', [{numero:-5},{numero:40},{numero:120}], 'Prueba valores por debajo, dentro y por encima del rango.'),
        T('Define limpiar(s) como strip().lower(), comprueba limpiar(" SQL ")=="sql" y aplica a texto.', "def limpiar(s):\n    return s.strip().lower()\nassert limpiar(' SQL ') == 'sql'\nresultado = limpiar(texto)", [{texto:' PYTHON '},{texto:''},{texto:'Hola'}], 'La prueba conserva una expectativa durante cambios futuros.'),
      ]),
  ]),
  unit('python-sql', '12 · Proyectos Python + SQL', 'sqlite3, parámetros y pequeñas herramientas completas.', 'python', [
    L('sqlite', 'Python pregunta a SQL', 'sqlite3 conecta Python con SQLite. En Habla connect solo acepta :memory:, para practicar sin alterar archivos reales.',
      [['sqlite3.connect','Abre una base de datos SQLite'],['execute','Ejecuta una sentencia SQL'],['fetchall','Obtiene todas las filas del resultado']],
      "import sqlite3\ndb = sqlite3.___(':memory:')", 'connect', ['open','load'],
      E("':memory:' guarda los datos…", 'Solo mientras la conexión existe', ['En habla.db','En GitHub'], 'Es una base desechable dentro de la memoria del proceso.'), [
        T('Crea SQLite en memoria, tabla scores(points INTEGER), inserta puntos con un parámetro y devuelve SUM(points) como número.', "import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE scores(points INTEGER)')\ndb.execute('INSERT INTO scores VALUES(?)',(puntos,))\nresultado = db.execute('SELECT SUM(points) FROM scores').fetchone()[0]\ndb.close()", [{puntos:12},{puntos:0},{puntos:-2}], 'fetchone devuelve una tupla; [0] extrae la primera columna.', {bug:"import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE scores(points INTEGER)')\ndb.execute('INSERT INTO scores VALUES(?)',(puntos,))\nresultado = db.execute('SELECT SUM(points) FROM scores').fetchone()"}),
        T('Crea nums(n INTEGER), inserta numeros con executemany y devuelve COUNT(*) como entero.', "import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE nums(n INTEGER)')\ndb.executemany('INSERT INTO nums VALUES(?)',[(n,) for n in numeros])\nresultado = db.execute('SELECT COUNT(*) FROM nums').fetchone()[0]\ndb.close()", [{numeros:[1,2,3]},{numeros:[]},{numeros:[0]}], 'executemany recibe una colección de tuplas.'),
        T('Crea nums(n INTEGER), inserta numeros y devuelve sus valores ordenados como lista plana.', "import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE nums(n INTEGER)')\ndb.executemany('INSERT INTO nums VALUES(?)',[(n,) for n in numeros])\nresultado = [fila[0] for fila in db.execute('SELECT n FROM nums ORDER BY n').fetchall()]\ndb.close()", [{numeros:[3,1,2]},{numeros:[]},{numeros:[-1,0]}], 'La comprensión convierte filas de una columna en valores.'),
      ]),
    L('parameters', 'Consultas con entradas', 'Usa marcadores ? y una tupla separada para valores. Concatenar entradas dentro del SQL produce errores y riesgos de inyección.',
      [['?','Marcador para un valor parametrizado'],['Tupla de parámetros','Entrega valores separados de la sentencia SQL'],['Inyección SQL','Entrada que altera una sentencia construida como texto']],
      "db.execute('SELECT n FROM nums WHERE n > ___',(limite,))", '?', ['limite','{}'],
      E('¿Dónde colocar un valor que introduce el usuario?', 'En el argumento de parámetros de execute', ['En una f-string del SQL','Concatenado después de WHERE'], 'Los parámetros mantienen los datos separados de la estructura del SQL.'), [
        T('Crea nums e inserta numeros. Devuelve valores mayores que limite ordenados, usando ?.', "import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE nums(n INTEGER)')\ndb.executemany('INSERT INTO nums VALUES(?)',[(n,) for n in numeros])\nresultado = [fila[0] for fila in db.execute('SELECT n FROM nums WHERE n > ? ORDER BY n',(limite,)).fetchall()]\ndb.close()", [{numeros:[1,4,8],limite:4},{numeros:[],limite:0},{numeros:[0,-1,2],limite:-1}], 'La frontera estricta excluye valores iguales.', {bug:"import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE nums(n INTEGER)')\ndb.executemany('INSERT INTO nums VALUES(?)',[(n,) for n in numeros])\nresultado = [fila[0] for fila in db.execute('SELECT n FROM nums WHERE n >= ? ORDER BY n',(limite,)).fetchall()]"}),
        T('Inserta nombre en names(name TEXT) con un parámetro y léelo en resultado. Debe admitir apóstrofes.', "import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE names(name TEXT)')\ndb.execute('INSERT INTO names VALUES(?)',(nombre,))\nresultado = db.execute('SELECT name FROM names').fetchone()[0]\ndb.close()", [{nombre:"O'Brien"},{nombre:'Ana'},{nombre:"x'); DROP TABLE names; --"}], 'El texto entero se trata como dato, nunca como SQL.'),
        T('Crea nums, inserta numeros y cuenta valores >= minimo y <= maximo usando dos parámetros.', "import sqlite3\ndb = sqlite3.connect(':memory:')\ndb.execute('CREATE TABLE nums(n INTEGER)')\ndb.executemany('INSERT INTO nums VALUES(?)',[(n,) for n in numeros])\nresultado = db.execute('SELECT COUNT(*) FROM nums WHERE n BETWEEN ? AND ?',(minimo,maximo)).fetchone()[0]\ndb.close()", [{numeros:[1,2,3,4],minimo:2,maximo:3},{numeros:[],minimo:0,maximo:10},{numeros:[0,1],minimo:0,maximo:0}], 'BETWEEN incluye ambas fronteras.'),
      ]),
    L('final-projects', 'Tu caja de proyectos', 'Resuelve problemas completos combinando limpieza, agrupación y cálculos. Nombra variables por su función y prueba también colecciones vacías.',
      [['Pipeline','Secuencia de transformación de datos'],['Agrupación','Acumula valores bajo una clave común'],['Contrato','Define entradas, resultados y casos extremos']],
      'totales[ciudad] = totales.get(ciudad,0) ___ importe', '+', ['=','-'],
      E('Para comprobar que un proyecto sirve con datos nuevos…', 'Prueba entradas distintas y casos extremos', ['Usa solo el ejemplo resuelto','Copia la salida esperada como constante'], 'Los ejemplos son pistas, no valores que debas fijar dentro del código.'), [
        T('registros es una lista de {ciudad,importe}. Suma importes por ciudad normalizada con strip y lower.', "resultado = {}\nfor registro in registros:\n    ciudad = registro['ciudad'].strip().lower()\n    resultado[ciudad] = resultado.get(ciudad,0) + registro['importe']", [{registros:[{ciudad:' Madrid ',importe:10},{ciudad:'madrid',importe:5},{ciudad:'Bilbao',importe:2}]},{registros:[]},{registros:[{ciudad:' SQL ',importe:0}]}], 'Limpia antes de agrupar para unir claves equivalentes.', {bug:"resultado = {}\nfor registro in registros:\n    ciudad = registro['ciudad']\n    resultado[ciudad] = registro['importe']"}),
        T('productos contiene {nombre,precio,stock}. Devuelve nombres únicos ordenados de productos con stock>0 y precio<=presupuesto.', "resultado = sorted({p['nombre'] for p in productos if p['stock']>0 and p['precio']<=presupuesto})", [{productos:[{nombre:'A',precio:5,stock:2},{nombre:'B',precio:10,stock:0}],presupuesto:5},{productos:[],presupuesto:0},{productos:[{nombre:'A',precio:5,stock:1},{nombre:'A',precio:5,stock:2}],presupuesto:5}], 'Combina filtro, conjunto y ordenación.'),
        T('texto contiene una lista JSON de {nombre,puntos}. Devuelve [nombre,puntos] de los 3 mejores, por puntos DESC y nombre ASC.', "import json\njugadores = json.loads(texto)\nordenados = sorted(jugadores,key=lambda j:(-j['puntos'],j['nombre']))\nresultado = [[j['nombre'],j['puntos']] for j in ordenados[:3]]", [{texto:'[{"nombre":"Luis","puntos":10},{"nombre":"Ana","puntos":10},{"nombre":"Sol","puntos":5},{"nombre":"Eva","puntos":1}]'},{texto:'[]'},{texto:'[{"nombre":"Sol","puntos":0}]'}], 'La clave de ordenación combina una métrica descendente con un desempate.'),
      ]),
  ]),
];
