// Correcciones docentes revisadas. Los identificadores se conservan para mantener el progreso.
export const goals = {
  436: 'La variable puntos ya contiene un número. Crea una variable llamada resultado con ese mismo valor, sin cambiarlo.',
  438: 'La variable monedas ya contiene una cantidad. Multiplica esa cantidad por 2 y guarda el número obtenido en resultado.',
  440: 'La variable nombre ya contiene un texto. Guarda ese mismo texto en resultado; no escribas literalmente la palabra "nombre".',
  464: 'Construye un texto repitiendo el contenido de simbolo tantas veces como indique el número veces. Si veces vale 0, el texto debe quedar vacío.',
  478: 'Separa frase en una lista de palabras. Ignora los espacios al principio y al final y trata varios espacios seguidos como un único separador.',
  484: 'Guarda True en resultado si edad es mayor o igual que 18; en otro caso guarda False.',
  486: 'Guarda True solo si puntos es mayor o igual que 10 y vidas es mayor que 0. En cualquier otro caso, guarda False.',
  488: 'Guarda True si nombre contiene al menos un carácter, y False si es el texto vacío "". Un espacio también cuenta como carácter: no uses strip en este ejercicio.',
  496: 'Si stock es mayor que 0, calcula precio por cantidad. Si stock vale 0, el resultado debe ser 0. En este ejercicio simplificado solo importa si hay existencias, no si alcanzan para toda la cantidad.',
  518: 'Duplica valor repetidamente mientras sea menor que limite. Guarda el valor final, que puede superar el límite. Si ya lo alcanza, no lo cambies. La entrada valor siempre es positiva.',
  528: 'Construye una lista con los números anteriores al primer 0 de numeros, sin incluirlo. Si no hay ningún 0, incluye todos; si el primero es 0, devuelve una lista vacía.',
  542: 'Guarda una lista con los dos números mayores de numeros, ordenados de mayor a menor. Conserva los duplicados. Si hay menos de dos elementos, incluye los que haya.',
  548: 'punto es una secuencia de dos números, [x, y]. Desempaquétala en las variables x e y y guarda su suma en resultado.',
  556: 'ficha es un diccionario. Guarda en resultado el valor de su clave "puntos"; si esa clave no existe, guarda 0.',
  558: 'Crea una copia del diccionario ficha y guarda en su clave "nivel" el valor de la variable nivel. Sustituye esa clave si ya existe y guarda el diccionario completo en resultado.',
  564: 'Construye un diccionario con cada palabra distinta de palabras como clave y su número de apariciones como valor. No cambies mayúsculas ni espacios. Una lista vacía debe producir {}.',
  584: 'Define es_par(n), que devuelve True si n es divisible entre 2 y False si no. Llama a la función con la variable numero y guarda ese booleano en resultado.',
  588: 'Define saludar(nombre, saludo="Hola"), que devuelve el saludo, una coma y un espacio, y el nombre. Llama a la función con las variables de entrada nombre y saludo, pasando saludo por nombre, y guarda el texto en resultado.',
  590: 'Define multiplicar(n, factor=2), que devuelve n por factor. Guarda en resultado una lista de dos números: primero multiplicar(n) con el factor por defecto y después multiplicar(n, factor=3).',
  592: 'Define agregar(x, items=None): si no recibe lista, crea una nueva; añade x y devuelve esa lista. Guarda [agregar(a), agregar(b)] en resultado. Las dos llamadas deben crear listas independientes.',
  596: 'Define descontar(precio, porcentaje), que calcula precio por (1 - porcentaje/100) y redondea a dos decimales con round. Llama a la función con las dos variables de entrada y guarda su respuesta en resultado.',
  600: 'Define normalizar(texto), que elimina espacios extremos y convierte a minúsculas. Aplica la función a cada texto de nombres y guarda la lista completa en resultado, conservando el orden.',
  616: 'Construye un diccionario que asocie cada elemento de nombres con el elemento de puntos situado en la misma posición. Usa zip: si las listas tienen distinta longitud, ignora los elementos sobrantes.',
  624: 'Define un generador pares(n) que produzca los enteros pares desde 0 hasta n, incluido n si es par. Guarda list(pares(n)) en resultado. n es un entero no negativo.',
  648: 'Importa json y convierte texto, que siempre contiene un objeto JSON válido, en un diccionario. Guarda el valor de la clave "puntos" o 0 si la clave no existe.',
  656: 'Lee el archivo virtual notas.txt y cuenta sus líneas usando readlines. Las líneas vacías cuentan; un salto de línea al final no crea una línea adicional.',
  664: 'texto es un CSV sencillo con cabecera nombre,puntos en la primera línea. Omite esa cabecera y las líneas vacías; guarda los puntos de cada fila como lista de enteros, en el orden original.',
  670: 'Convierte el diccionario datos en un texto JSON usando json.dumps(datos, sort_keys=True). Usa los separadores por defecto: incluye un espacio después de cada coma y de cada dos puntos. Guarda el texto, no el diccionario, en resultado.',
  672: 'texto contiene una lista JSON de objetos con nombre y, opcionalmente, activo. Guarda una lista de los nombres cuyo activo sea true, conservando el orden. Si falta activo, considera false.',
  678: 'Define una clase Producto y crea una instancia p. Asigna el valor de precio a su atributo p.price y guarda p.price por cantidad en resultado.',
  680: 'Define la clase Personaje y crea dos instancias diferentes. Asigna a al atributo name de la primera y b al de la segunda. Guarda sus dos nombres en una lista, en ese orden.',
  684: 'Define Cuenta con el método deposit(self, cantidad), que suma cantidad a self.balance. Crea una cuenta, inicializa balance con saldo y deposita importe. Guarda el balance final en resultado.',
  686: 'Define Producto.total(self, cantidad), que devuelve self.price por cantidad. Crea p, asigna precio a p.price, llama a p.total(cantidad) y guarda el número devuelto en resultado.',
  688: 'Define Persona.label(self), que devuelve "Hola, " seguido de self.name. Crea una persona, asigna nombre a su atributo name y guarda el texto devuelto por label() en resultado.',
  694: 'Define limitar(n), que devuelve 0 si n<0, 100 si n>100 y n en otro caso. Comprueba con assert que limitar(-1)==0 y limitar(101)==100. Guarda limitar(numero) en resultado.',
  708: 'Crea una base SQLite en memoria y la tabla nums(n INTEGER). Inserta todos los elementos de numeros. Consulta los valores estrictamente mayores que limite usando un marcador ?. Guarda una lista plana de números de menor a mayor, conservando repeticiones.',
  710: 'Crea una base SQLite en memoria y la tabla names(name TEXT). Inserta la variable nombre con un marcador ? y una tupla de parámetros. Lee ese nombre y guárdalo como texto en resultado. Debe funcionar aunque contenga un apóstrofo.',
  712: 'Crea una base SQLite en memoria y la tabla nums(n INTEGER). Inserta numeros y cuenta los valores comprendidos entre minimo y maximo, ambos incluidos. Usa dos marcadores ? y guarda el recuento como entero en resultado.',
  716: 'registros es una lista de diccionarios con ciudad e importe. Normaliza cada ciudad eliminando espacios extremos y convirtiendo a minúsculas. Guarda un diccionario que sume los importes por ciudad normalizada. Si registros está vacío, devuelve {}.',
  718: 'productos es una lista de diccionarios con nombre, precio y stock. Selecciona los que tienen stock>0 y precio<=presupuesto. Guarda una lista de sus nombres, sin duplicados y en orden alfabético.',
  720: 'texto contiene una lista JSON de jugadores con nombre y puntos. Ordena por puntos de mayor a menor y, en empates, por nombre alfabético. Guarda hasta tres parejas [nombre, puntos] en una lista; si hay menos de tres jugadores, incluye los disponibles.',
  228: 'Calcula la suma de quantity de todos los pedidos de orders, sin filtrar por estado, y llámala units. Si no hay pedidos, el resultado debe ser NULL, no 0.',
  230: 'Calcula la media de las notas grade conocidas de students, ignorando NULL, y redondéala a dos decimales. Llama a la columna mean_grade. Si no hay notas conocidas, devuelve NULL.',
  248: 'Suma quantity por customer_id de orders, incluyendo todos los estados. Devuelve customer_id y la suma con el alias units solo cuando supere 5.',
  268: 'Relaciona customers y orders por customers.id = orders.customer_id. Muestra el nombre del cliente y el id del pedido con alias order_id. Devuelve una fila por pedido: un cliente con varios pedidos aparece varias veces.',
  272: 'Relaciona orders con customers y products. Para cada pedido con status="paid", muestra el nombre del cliente y el nombre del producto con alias product. Conserva una fila por pedido, aunque se repita un cliente o producto.',
  276: 'Muestra una fila por pedido con el nombre de su cliente y el id del pedido como order_id. Incluye también a los clientes sin pedidos: su order_id debe ser NULL. Usa customers como tabla izquierda.',
  280: 'Cuenta los pedidos de cada cliente identificado por customers.id. Devuelve name y el recuento con alias orders_count. Incluye clientes sin pedidos con recuento 0; no cuentes la fila artificial del LEFT JOIN.',
  288: 'Calcula los ingresos por cliente a partir de quantity por price, contando solo pedidos paid. Devuelve name y revenue para todos los clientes, incluidos quienes no tienen pedidos pagados: su revenue debe ser 0. Agrupa por identidad del cliente, no solo por nombre.',
  304: 'Muestra name y el cociente price/stock redondeado a dos decimales con alias ratio. Usa división decimal. Cuando stock sea 0, devuelve NULL mediante NULLIF. Es una práctica de división segura, no una métrica de ventas.',
  308: 'Muestra id de todos los pedidos de enero de 2026, sin filtrar su estado. Incluye desde 2026-01-01 y excluye desde 2026-02-01.',
  310: 'Agrupa todos los pedidos por su mes de ordered_at. Devuelve el mes como texto YYYY-MM con alias month y el número de pedidos como total. No inventes filas para meses sin pedidos.',
  312: 'Para cada pedido muestra id y una fecha hipotética de entrega: siete días después de ordered_at, con alias delivery y formato YYYY-MM-DD.',
  328: 'Muestra el nombre de cada cliente que no tenga ningún pedido paid. Incluye a quienes no tienen pedidos y a quienes solo tienen pedidos pending o cancelled.',
  376: 'Para cada empleado muestra name y la diferencia entre su salary y la suma de salarios de todo su department, con alias gap. Incluye su propio salario en la suma. No es una diferencia con la media: el resultado suele ser negativo.',
  380: 'Muestra id y la suma acumulada de quantity con alias running_units, incluyendo todos los estados de pedido. Avanza por ordered_at ASC y, si hay empate, por id ASC. Ordena también las filas finales así.',
  382: 'Muestra id y la cantidad quantity del pedido anterior como previous_units. La secuencia es ordered_at ASC, id ASC; la primera fila debe tener NULL. Ordena también las filas finales así.',
  384: 'Muestra id y la diferencia entre quantity actual y quantity del pedido anterior como change, siguiendo ordered_at ASC, id ASC. Para la primera fila toma la cantidad anterior como 0. Ordena también las filas finales así.',
  414: 'Crea el índice idx_orders_status_date sobre orders(status, ordered_at). Muestra después id de pedidos paid de febrero de 2026: desde 2026-02-01 incluido hasta 2026-03-01 excluido.',
  420: 'Identifica ciudades compartidas por más de un cliente: devuelve city y el recuento como total. Aquí una ciudad repetida no significa que los clientes sean duplicados.',
  424: 'Busca pedidos cuyo customer_id no corresponda a ningún customers.id. Muestra solo el id del pedido. En los datos iniciales no hay huérfanos, pero tu consulta debe detectarlos cuando aparezcan.',
  430: 'Muestra name de un empleado por departamento: el de mayor salary. En un empate elige el menor id. Practica una CTE con ROW_NUMBER y filtra la posición 1.',
  432: 'Calcula ingresos de pedidos paid por mes: quantity por price, sumado por el mes de ordered_at. Muestra month en formato YYYY-MM y revenue. Ordena por month ASC. Solo deben aparecer meses con pedidos pagados; si no hay ninguno, devuelve cero filas.',
};

export const basics = [
 ['Tu primera consulta','SELECT y FROM','Una base de datos guarda tablas. Cada fila de students representa un estudiante y cada columna representa un dato: id, name, age, city o grade. SELECT elige las columnas y FROM indica de qué tabla leerlas.', ['SELECT name FROM students; muestra solo los nombres.','SELECT * FROM students; muestra todas las columnas.','Termina las sentencias con ;. En el editor, una única consulta también funciona sin el punto y coma final.']],
 ['Ordena los resultados','ORDER BY','Sin ORDER BY, el orden de las filas no está garantizado. ORDER BY age ordena por edad de menor a mayor; DESC invierte ese orden.', ['ASC es el orden ascendente y se usa por defecto. DESC es descendente.','Para desempatar por edad, escribe ORDER BY age, id.','El orden escrito es SELECT, FROM, ORDER BY y LIMIT. LIMIT 3 devuelve como máximo tres filas.']],
 ['Nombres y resultados únicos','AS y DISTINCT','AS cambia el nombre de una columna en el resultado, sin modificar la tabla. DISTINCT elimina filas duplicadas del resultado; no ordena las filas.', ['SELECT name AS student FROM students; llama student a la columna de nombres.','SELECT DISTINCT city FROM students; devuelve cada ciudad una sola vez.','Si necesitas un orden alfabético, añade ORDER BY city.']],
 ['Selecciona las filas que necesitas','WHERE','WHERE conserva las filas que cumplen una condición. Se escribe después de FROM y antes de ORDER BY. Los textos van entre comillas simples; los números pueden escribirse sin ellas.', ['WHERE city = \'Madrid\' compara una ciudad con un texto. WHERE age = 20 compara números.','Usa = para igualdad, <> para desigualdad y >, <, >= o <= para comparar límites.','SQLite también acepta == e IS en ciertos casos. Practicamos = por ser el operador habitual y más portable para comparar valores.']],
 ['Combina condiciones','AND, OR, IN y BETWEEN','AND exige que se cumplan las dos condiciones; OR exige al menos una. IN compara con una lista de valores y BETWEEN expresa un intervalo con sus dos extremos incluidos.', ['city IN (\'Madrid\', \'Sevilla\') significa Madrid o Sevilla.','age BETWEEN 19 AND 22 incluye 19, 20, 21 y 22.','AND tiene prioridad sobre OR. Usa paréntesis para expresar, por ejemplo, (city=\'Madrid\' OR city=\'Bilbao\') AND age<22.']],
 ['Patrones y datos desconocidos','LIKE y NULL','LIKE busca patrones de texto: % representa cero o más caracteres y _ representa exactamente uno. NULL indica un valor desconocido, no un cero ni un texto vacío.', ['LIKE \'A%\' busca nombres que empiezan por A; en SQLite también coincide con a para caracteres ASCII.','LIKE \'%ar%\' busca ar en cualquier posición.','IS NULL busca datos desconocidos; IS NOT NULL busca datos presentes. grade = NULL no conserva ninguna fila.']],
];

// [enunciado, explicación, opciones/banco/significados opcionales, pregunta opcional]
export const basicExercises = {
 97:['En la tabla students, ¿qué representa una fila?','Una fila contiene los datos de un estudiante. Una columna, como age, contiene un tipo de dato de todos los estudiantes.',['Un estudiante con todos sus datos','Un dato de todos los estudiantes','El nombre de la tabla','El número de estudiantes']],
 98:['¿Qué consulta muestra todas las columnas de todos los estudiantes?','SELECT elige las columnas y FROM la tabla. El asterisco * representa todas las columnas.'],
 99:['Relaciona cada elemento de SQL con su función.','Las palabras clave no distinguen mayúsculas y minúsculas; escribirlas en mayúsculas facilita la lectura.',{SELECT:'elige las columnas que se muestran',FROM:'indica la tabla que se lee','*':'todas las columnas',';':'termina una sentencia'}],
 100:['Completa la consulta para mostrar todas las columnas de students.','FROM introduce la tabla que se va a leer.'],
 101:['Ordena las piezas: muestra solo la columna name de students.','Sustituye * por name para pedir únicamente los nombres. No se modifican los datos almacenados.'],
 102:['¿Qué consulta muestra las columnas name y city de students?','Las columnas se separan con comas; AND sirve para combinar condiciones.'],
 103:['Una consulta devuelve filas y columnas. Completa el nombre de esa respuesta.','Se llama conjunto de resultados. No es una copia permanente de la tabla.', ['resultados','consultas','órdenes','condiciones'],'La respuesta de una consulta es un conjunto de ___.'],
 104:['Ordena las piezas: muestra id y después name de todos los estudiantes.','El orden de las columnas del resultado es el mismo que en SELECT: primero id y después name.'],
 105:['¿Qué consulta ordena los estudiantes de menor a mayor edad?','El orden escrito es SELECT, FROM, ORDER BY. ASC es ascendente y se usa por defecto.'],
 106:['Relaciona cada palabra clave con su efecto.','ORDER BY ordena; ASC y DESC eligen la dirección; LIMIT reduce el número de filas.',{'ORDER BY':'ordena las filas',ASC:'menor primero (por defecto)',DESC:'mayor primero',LIMIT:'como máximo este número de filas'}],
 107:['Completa: muestra primero las notas más altas.','DESC ordena de mayor a menor. En SQLite los NULL quedan después de los números en este orden.'],
 108:['¿Qué devuelve esta consulta?','ORDER BY name ordena las filas por nombre, pero no cambia las columnas seleccionadas ni elimina estudiantes.',['Todos los estudiantes, ordenados alfabéticamente por nombre','Solo la columna name','Todos los estudiantes, en orden alfabético inverso','Solo estudiantes cuyo nombre empieza por A']],
 109:['Ordena las piezas: muestra todas las columnas y ordena por city.','ORDER BY se escribe después de FROM y antes de LIMIT.'],
 110:['¿Qué consulta devuelve como máximo los tres estudiantes de mayor edad?','Primero ordena age DESC y después aplica LIMIT 3. Si hay menos de tres estudiantes, devuelve los disponibles.'],
 111:['Completa la consulta para devolver como máximo cinco filas.','LIMIT 5 limita la cantidad, pero no garantiza cuáles son esas filas si no añades ORDER BY.'],
 112:['Ordena las piezas: muestra un estudiante con la nota más alta.','ORDER BY grade DESC LIMIT 1 coloca las notas más altas primero y toma una fila. Si hay empate, esta consulta no determina cuál elige.'],
 113:['¿Qué cambia esta consulta con AS?','AS cambia solo la etiqueta de la columna en esta respuesta, no el nombre almacenado en la tabla.',['Solo el nombre de la columna en el resultado','El nombre de la columna en la tabla','El orden de las filas','Las filas que se devuelven']],
 114:['Completa la consulta para llamar hometown a la columna city del resultado.','La forma es columna AS alias. El alias no modifica la tabla.'],
 115:['city contiene Madrid, Sevilla, Madrid y Valencia. ¿Qué devuelve SELECT DISTINCT city FROM students;?','DISTINCT elimina la repetición de Madrid. El orden no está garantizado sin ORDER BY.',['Tres filas: Madrid, Sevilla y Valencia, sin orden garantizado','Cuatro filas, con Madrid dos veces','Solo una fila: Madrid','Dos filas: Sevilla y Valencia']],
 116:['Relaciona cada herramienta con su función.','Estas cláusulas cambian el resultado de SELECT; no modifican las filas almacenadas.',{AS:'renombra una columna en el resultado',DISTINCT:'elimina filas duplicadas del resultado','ORDER BY':'ordena las filas del resultado',LIMIT:'limita el número de filas del resultado'}],
 117:['Ordena las piezas: muestra cada ciudad de students una sola vez.','DISTINCT va inmediatamente después de SELECT y se aplica a la fila completa del resultado.'],
 118:['¿Cuál es la consulta válida para listar ciudades únicas y ordenarlas?','SELECT DISTINCT city FROM students ORDER BY city; elimina repeticiones y después ordena.'],
 119:['Escribe una consulta que muestre todas las columnas y todas las filas de students.','SELECT * FROM students; utiliza * para pedir todas las columnas. También puedes enumerarlas si conservas sus nombres y orden.'],
 120:['Ordena las piezas: los dos primeros nombres alfabéticos, con alias student.','AS renombra la columna; ORDER BY name ordena y LIMIT 2 conserva como máximo dos filas.'],
 121:['¿Qué consulta muestra todas las columnas de estudiantes con más de 20 años?','WHERE age > 20 excluye a quienes tienen exactamente 20. WHERE se escribe después de FROM.'],
 122:['Completa usando el operador habitual de igualdad para filtrar Madrid.','= es el operador habitual de igualdad. SQLite acepta también == y ciertas comparaciones con IS, así que no son errores de sintaxis en este motor.',['=','<>','>','<']],
 123:['Relaciona cada operador con su significado.','<> y != expresan desigualdad. Las comparaciones con NULL necesitan IS NULL o IS NOT NULL.',{'=':'es igual a','<>':'es distinto de','>=':'es mayor o igual que','<':'es menor que'}],
 124:['La tabla students no tiene una columna Madrid. ¿Por qué falla WHERE city = Madrid sin comillas?','Sin comillas, Madrid se interpreta como un identificador. Para comparar con el texto de la ciudad, escribe city = \'Madrid\'.',['Busca una columna llamada Madrid que no existe','Las ciudades deben escribirse en mayúsculas','WHERE solo compara números','Las comillas nunca son necesarias']],
 125:['Ordena las piezas: nombres de estudiantes con grade menor que 7.','Puedes filtrar por grade sin mostrar esa columna. Las notas NULL no cumplen grade < 7.'],
 126:['¿Qué consulta coloca las cláusulas en el orden correcto?','El orden escrito es SELECT, FROM, WHERE, ORDER BY, LIMIT.'],
 127:['Completa: estudiantes cuya edad es exactamente 20.','WHERE filtra filas; HAVING filtra grupos de un resultado agregado.'],
 128:['Ordena las piezas: todas las columnas de estudiantes de Sevilla.','\'Sevilla\' es un texto y necesita comillas simples. Las palabras clave no distinguen mayúsculas; los textos con = normalmente sí en este laboratorio.'],
 129:['¿Qué consulta exige tener más de 20 años y ser de Madrid a la vez?','AND exige ambas condiciones. OR incluiría filas que cumplan solo una.'],
 130:['Para las mismas condiciones A y B, ¿qué filtro incluye todas las filas de A AND B y puede añadir otras?','A OR B acepta al menos una condición; por eso incluye todas las filas que satisfacen ambas.',['A OR B','A AND NOT B','NOT A AND NOT B','Ninguno: siempre devuelven lo mismo']],
 131:['Completa: estudiantes de Madrid o de Sevilla.','OR acepta cualquiera de las dos ciudades. Un mismo valor de city no puede ser Madrid y Sevilla a la vez.'],
 132:['Relaciona cada palabra clave con su significado.','BETWEEN incluye ambos extremos e IN compara con cualquiera de los valores de su lista.',{AND:'ambas condiciones deben cumplirse',OR:'al menos una condición debe cumplirse',IN:'coincide con algún valor de una lista',BETWEEN:'está en un intervalo, incluidos sus extremos'}],
 133:['Si age es una edad entera, ¿qué valores admite age BETWEEN 19 AND 22?','Los dos extremos están incluidos: equivale a age >= 19 AND age <= 22.',['19, 20, 21 y 22','Solo 20 y 21','Solo 19 y 22','Cualquier edad mayor que 19']],
 134:['Ordena la condición para aceptar Madrid o Sevilla usando IN.','La lista va entre paréntesis. Separa los textos con comas y encierra cada uno entre comillas simples.'],
 135:['Completa: ciudades distintas de Valencia. Supón que city no contiene NULL.','<> expresa desigualdad. Si city fuera NULL, esta comparación no conservaría esa fila.'],
 136:['Ordena las piezas: nombres de estudiantes entre 19 y 22 años, incluidos ambos, ordenados por edad.','El AND de BETWEEN separa sus dos límites; ORDER BY age ordena ascendentemente.'],
 137:['¿Qué nombres admite name LIKE \'A%\' en este laboratorio?','% representa cero o más caracteres. SQLite LIKE no distingue A y a para caracteres ASCII por defecto.',['Nombres que empiezan por A o a, como Ana','Nombres que terminan en A','Nombres que contienen A en cualquier posición','Solo el texto literal A%']],
 138:['Completa el patrón para buscar ar en cualquier posición del nombre.','Un % a cada lado permite cualquier texto antes y después de ar.'],
 139:['Todavía no conocemos la nota de Diego. ¿Cómo la representamos en grade?','NULL significa dato desconocido. No equivale a una nota de cero ni a un texto vacío.',['NULL: nota desconocida','0: nota de cero','Un texto vacío','El texto none']],
 140:['¿Qué consulta encuentra estudiantes con grade desconocido?','grade IS NULL detecta valores desconocidos. grade = NULL produce NULL, no True, y WHERE no conserva esas filas.'],
 141:['Relaciona cada condición con lo que busca.','IS NULL y IS NOT NULL comprueban presencia de datos; LIKE comprueba patrones de texto.',{'IS NULL':'filas con dato desconocido','IS NOT NULL':'filas con dato presente',"LIKE 'M%'":'textos que empiezan por M o m',"LIKE '%o'":'textos que terminan en o u O'}],
 142:['Completa: estudiantes que sí tienen una nota registrada.','IS NOT NULL incluye también una nota de cero, porque cero es un valor conocido.'],
 143:['Ordena las piezas: estudiantes cuyo nombre empieza por M o m.','El patrón \'M%\' va entre comillas simples. SQLite LIKE también coincide con m para ASCII.'],
 144:['¿Qué consulta encuentra estudiantes de Madrid que ya tienen nota?','Combina city = \'Madrid\' con grade IS NOT NULL mediante AND. En SQLite IS también puede comparar textos; no se usa aquí como opción incorrecta.'],
};
